name: flake8_py_version_check
on:
  workflow_dispatch: {}
  schedule:
  # every Sunday at midnight
  - cron: "0 0 * * 0"
jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python3
      uses: actions/setup-python@v6
      with:
        allow-prereleases: true
    - name: run script
      run: python scripts/flake8_py_version_check.py
